server:
  port: 8080
  dashboard_port: 8081
  aliases:
    falco: "/falco"
    cilium: "/cilium"

scenarios:
  block_ip:
    wait_timeout: 300 # секунди
    trigger_count: 3  # Кількість спрацьовувань
    trigger_window: 3600 # Вікно в секундах (1 година)
    unblock_after: 600 # Час блокування в секундах
    actioners:
      - gcp_firewall
      - gcp_storage

actioners:
  gcp_firewall:
    project_id: "my-gcp-project"
    credentials_file: "path/to/credentials.json"
  gcp_storage:
    project_id: "my-gcp-project"
    bucket_name: "my-logs-bucket"
    log_count: 100
    credentials_file: "path/to/credentials.json"

notifier:
  slack:
    webhook_url: "https://hooks.slack.com/services/xxx/yyy/zzz"
    callback_url: "http://localhost:8080/callback"