server:
  port: ":8080"
  aliases:
    "/falco": "falco_events"
    "/cilium": "cilium_events"

scenarios:
  - name: "block_ip"
    falco_rule: "Suspicious Network Activity"
    conditions:
      trigger_count: 3
      time_window: "3600s"
    actioners:
      - name: "firewall"
        params:
          priority: 1000
          description: "Blocked by Falco rule"
          timeout: "1m"  # Час блокування в форматі Go duration (наприклад, "5m" = 5 хвилин)
      - name: "storage"
        params:
          prefix: "blocked_ips/"

actioners:
  firewall:
    type: "gcp_firewall"
    params:
      project_id: "my-project"
      timeout: 60  # Базове значення, якщо не задано в сценарії
  storage:
    type: "gcp_storage"
    params:
      bucket_name: "my-logs-bucket"
      log_count: 100