server:
  port: ":8080"
  aliases:
    "/falco": "falco_events"
    "/cilium": "cilium_events"

scenarios:
  - name: "block_ip"
    falco_rule: "Suspicious Network Activity"
    conditions:
      trigger_count: 3
      time_window: "3600s"
    actioners:
      - name: "firewall"
        params:
          priority: 1000
          description: "Blocked by Falco rule"
          timeout: "5m"
      - name: "storage"
        params:
          prefix: "blocked_ips/"
      - name: "sigma"  # Новий діяч
        params:
          prefix: "sigma_rules/"

actioners:
  firewall:
    type: "gcp_firewall"
    params:
      project_id: "my-project"
      timeout: 60
      multiply_timeout: true
      credentials_file: "/path/to/firewall-service-account.json"
  storage:
    type: "gcp_storage"
    params:
      bucket_name: "my-logs-bucket"
      log_count: 100
      credentials_file: "/path/to/storage-service-account.json"
  sigma:
    type: "sigma_storage"  # Новий тип діяча
    params:
      bucket_name: "my-logs-bucket"  # Може бути окремий бакет
      credentials_file: "/path/to/sigma-service-account.json"